### ISSUE TITLE
sql/parser: integrate SHOW and DESCRIBE in the parser

### ISSUE THREAD

**Issue by smola** [src-d/gitquery#74]
Vitess SQL parser does not support SHOW and DESCRIBE. So we are currently matching them ad hoc before passing the query to the parser. They should be properly supported in the SQL parser, contributing it to Vitess or, if that's not possible, forking it.

**Comment by campoy** [comment]
Why was this closed?

SHOW and DESCRIBE are still not supported, which causes issues when using gitbase from some libraries, such as pymysql.

**Comment by ajnavarro** [comment]
This issue is closed because we move all that logic to https://github.com/src-d/go-mysql-server. You can see here a related issue: https://github.com/src-d/go-mysql-server/issues/5

SHOW is a huge statement: https://dev.mysql.com/doc/refman/5.5/en/show.html . Right now we have only implemented `SHOW TABLES;`.

On the other hand, we only have implemented `DESCRIBE TABLE tablename;`, not `SHOW COLUMNS FROM tablename`. Why? legacy code.
